/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mock from "./mock";
export type { mock };
export type { Bank } from "./Bank";
export type { LoanableBank } from "./LoanableBank";
export type { Lock } from "./Lock";
export type { RoleAccessControl } from "./RoleAccessControl";
export type { Utils } from "./Utils";
