/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Globals {
  export type PairStruct = {
    collateralToken: PromiseOrValue<string>;
    borrowToken: PromiseOrValue<string>;
  };

  export type PairStructOutput = [string, string] & {
    collateralToken: string;
    borrowToken: string;
  };

  export type LoanConfigStruct = {
    tokenPair: Globals.PairStruct;
    interest: PromiseOrValue<BigNumberish>;
    duration: PromiseOrValue<BigNumberish>;
    liquidationLTV: PromiseOrValue<BigNumberish>;
    enabled: PromiseOrValue<boolean>;
  };

  export type LoanConfigStructOutput = [
    Globals.PairStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    tokenPair: Globals.PairStructOutput;
    interest: BigNumber;
    duration: BigNumber;
    liquidationLTV: BigNumber;
    enabled: boolean;
  };

  export type LoanStruct = {
    tokenPair: Globals.PairStruct;
    collateralAmount: PromiseOrValue<BigNumberish>;
    borrowAmount: PromiseOrValue<BigNumberish>;
    ownedAmount: PromiseOrValue<BigNumberish>;
    created: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
    configId: PromiseOrValue<BytesLike>;
    paid: PromiseOrValue<boolean>;
  };

  export type LoanStructOutput = [
    Globals.PairStructOutput,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    boolean
  ] & {
    tokenPair: Globals.PairStructOutput;
    collateralAmount: BigNumber;
    borrowAmount: BigNumber;
    ownedAmount: BigNumber;
    created: BigNumber;
    deadline: BigNumber;
    configId: string;
    paid: boolean;
  };
}

export declare namespace Bank {
  export type TokenDescriptionStruct = {
    key: PromiseOrValue<BytesLike>;
    addr: PromiseOrValue<string>;
    symbol: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
  };

  export type TokenDescriptionStructOutput = [
    string,
    string,
    string,
    string
  ] & { key: string; addr: string; symbol: string; name: string };
}

export interface LoanableBankInterface extends utils.Interface {
  functions: {
    "ADMIN_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "OPERATOR_ROLE()": FunctionFragment;
    "OWNER_ROLE()": FunctionFragment;
    "addAdmin(address)": FunctionFragment;
    "addLoanConfig(((address,address),uint256,uint256,uint256,bool))": FunctionFragment;
    "addOperator(address)": FunctionFragment;
    "addPair((address,address))": FunctionFragment;
    "addToken(address)": FunctionFragment;
    "balances(address,bytes32)": FunctionFragment;
    "checkTokenAddress(address)": FunctionFragment;
    "deposit(address,uint256)": FunctionFragment;
    "disableLoanConfig(((address,address),uint256,uint256,uint256,bool))": FunctionFragment;
    "disablePair((address,address))": FunctionFragment;
    "getAllLoans()": FunctionFragment;
    "getAllPairs(bool)": FunctionFragment;
    "getBalance(address,address)": FunctionFragment;
    "getLTVs((address,address)[])": FunctionFragment;
    "getLoanConfigId((address,address),uint256,uint256)": FunctionFragment;
    "getLoanConfigKey(((address,address),uint256,uint256,uint256,bool))": FunctionFragment;
    "getLoanPreview((address,address),uint256,uint256,uint256)": FunctionFragment;
    "getPairKey((address,address))": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getSupportedTokens()": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "liquidateLoan(address)": FunctionFragment;
    "liquidator()": FunctionFragment;
    "loanConfigs(bytes32)": FunctionFragment;
    "oracle()": FunctionFragment;
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "payLoan(address,uint256)": FunctionFragment;
    "removeAdmin(address)": FunctionFragment;
    "removeLoanConfig(((address,address),uint256,uint256,uint256,bool))": FunctionFragment;
    "removeOperator(address)": FunctionFragment;
    "removePair((address,address))": FunctionFragment;
    "removeToken(address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "requestLoan((address,address),uint256,uint256,uint256)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "tokens(bytes32)": FunctionFragment;
    "transfer(address,address,uint256)": FunctionFragment;
    "transferBackOffice(address,address,address,uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateLoans()": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "OPERATOR_ROLE"
      | "OWNER_ROLE"
      | "addAdmin"
      | "addLoanConfig"
      | "addOperator"
      | "addPair"
      | "addToken"
      | "balances"
      | "checkTokenAddress"
      | "deposit"
      | "disableLoanConfig"
      | "disablePair"
      | "getAllLoans"
      | "getAllPairs"
      | "getBalance"
      | "getLTVs"
      | "getLoanConfigId"
      | "getLoanConfigKey"
      | "getLoanPreview"
      | "getPairKey"
      | "getRoleAdmin"
      | "getSupportedTokens"
      | "grantRole"
      | "hasRole"
      | "liquidateLoan"
      | "liquidator"
      | "loanConfigs"
      | "oracle"
      | "owner"
      | "paused"
      | "payLoan"
      | "removeAdmin"
      | "removeLoanConfig"
      | "removeOperator"
      | "removePair"
      | "removeToken"
      | "renounceOwnership"
      | "renounceRole"
      | "requestLoan"
      | "revokeRole"
      | "supportsInterface"
      | "tokens"
      | "transfer"
      | "transferBackOffice"
      | "transferOwnership"
      | "updateLoans"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OWNER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addLoanConfig",
    values: [Globals.LoanConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addOperator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addPair",
    values: [Globals.PairStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "balances",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTokenAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "disableLoanConfig",
    values: [Globals.LoanConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "disablePair",
    values: [Globals.PairStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllLoans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPairs",
    values: [PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLTVs",
    values: [Globals.PairStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanConfigId",
    values: [
      Globals.PairStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanConfigKey",
    values: [Globals.LoanConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanPreview",
    values: [
      Globals.PairStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPairKey",
    values: [Globals.PairStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSupportedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateLoan",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "loanConfigs",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payLoan",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeLoanConfig",
    values: [Globals.LoanConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removePair",
    values: [Globals.PairStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "removeToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [
      Globals.PairStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferBackOffice",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLoans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OWNER_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addLoanConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkTokenAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disableLoanConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disablePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPairs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLTVs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLoanConfigId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanConfigKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanPreview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPairKey", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSupportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidateLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeLoanConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removePair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferBackOffice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AdminGranted(address)": EventFragment;
    "AdminRevoked(address)": EventFragment;
    "BankerGranted(address)": EventFragment;
    "BankerRevoked(address)": EventFragment;
    "ConfigChanged(bytes32,uint8)": EventFragment;
    "Deposited(address,address,uint256)": EventFragment;
    "LoanCreated(address,bytes32,uint256,uint256)": EventFragment;
    "LoanLiquidated(address)": EventFragment;
    "LoanPaid(address,uint256,bool)": EventFragment;
    "OperatorGranted(address)": EventFragment;
    "OperatorRevoked(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "PairChanged(bytes32,uint8)": EventFragment;
    "Paused(address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "TokenChanged(bytes32,uint8)": EventFragment;
    "Transfered(address,address,address,uint256)": EventFragment;
    "Unpaused(address)": EventFragment;
    "Withdrew(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AdminRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BankerGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BankerRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ConfigChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanLiquidated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LoanPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OperatorGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OperatorRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PairChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrew"): EventFragment;
}

export interface AdminGrantedEventObject {
  addr: string;
}
export type AdminGrantedEvent = TypedEvent<[string], AdminGrantedEventObject>;

export type AdminGrantedEventFilter = TypedEventFilter<AdminGrantedEvent>;

export interface AdminRevokedEventObject {
  addr: string;
}
export type AdminRevokedEvent = TypedEvent<[string], AdminRevokedEventObject>;

export type AdminRevokedEventFilter = TypedEventFilter<AdminRevokedEvent>;

export interface BankerGrantedEventObject {
  addr: string;
}
export type BankerGrantedEvent = TypedEvent<[string], BankerGrantedEventObject>;

export type BankerGrantedEventFilter = TypedEventFilter<BankerGrantedEvent>;

export interface BankerRevokedEventObject {
  addr: string;
}
export type BankerRevokedEvent = TypedEvent<[string], BankerRevokedEventObject>;

export type BankerRevokedEventFilter = TypedEventFilter<BankerRevokedEvent>;

export interface ConfigChangedEventObject {
  configKey: string;
  operation: number;
}
export type ConfigChangedEvent = TypedEvent<
  [string, number],
  ConfigChangedEventObject
>;

export type ConfigChangedEventFilter = TypedEventFilter<ConfigChangedEvent>;

export interface DepositedEventObject {
  token: string;
  from: string;
  amount: BigNumber;
}
export type DepositedEvent = TypedEvent<
  [string, string, BigNumber],
  DepositedEventObject
>;

export type DepositedEventFilter = TypedEventFilter<DepositedEvent>;

export interface LoanCreatedEventObject {
  holder: string;
  configKey: string;
  ownedAmount: BigNumber;
  deadline: BigNumber;
}
export type LoanCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  LoanCreatedEventObject
>;

export type LoanCreatedEventFilter = TypedEventFilter<LoanCreatedEvent>;

export interface LoanLiquidatedEventObject {
  holder: string;
}
export type LoanLiquidatedEvent = TypedEvent<
  [string],
  LoanLiquidatedEventObject
>;

export type LoanLiquidatedEventFilter = TypedEventFilter<LoanLiquidatedEvent>;

export interface LoanPaidEventObject {
  holder: string;
  paidAmount: BigNumber;
  fullPayment: boolean;
}
export type LoanPaidEvent = TypedEvent<
  [string, BigNumber, boolean],
  LoanPaidEventObject
>;

export type LoanPaidEventFilter = TypedEventFilter<LoanPaidEvent>;

export interface OperatorGrantedEventObject {
  addr: string;
}
export type OperatorGrantedEvent = TypedEvent<
  [string],
  OperatorGrantedEventObject
>;

export type OperatorGrantedEventFilter = TypedEventFilter<OperatorGrantedEvent>;

export interface OperatorRevokedEventObject {
  addr: string;
}
export type OperatorRevokedEvent = TypedEvent<
  [string],
  OperatorRevokedEventObject
>;

export type OperatorRevokedEventFilter = TypedEventFilter<OperatorRevokedEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface PairChangedEventObject {
  configKey: string;
  operation: number;
}
export type PairChangedEvent = TypedEvent<
  [string, number],
  PairChangedEventObject
>;

export type PairChangedEventFilter = TypedEventFilter<PairChangedEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface RoleAdminChangedEventObject {
  role: string;
  previousAdminRole: string;
  newAdminRole: string;
}
export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string],
  RoleAdminChangedEventObject
>;

export type RoleAdminChangedEventFilter =
  TypedEventFilter<RoleAdminChangedEvent>;

export interface RoleGrantedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleGrantedEvent = TypedEvent<
  [string, string, string],
  RoleGrantedEventObject
>;

export type RoleGrantedEventFilter = TypedEventFilter<RoleGrantedEvent>;

export interface RoleRevokedEventObject {
  role: string;
  account: string;
  sender: string;
}
export type RoleRevokedEvent = TypedEvent<
  [string, string, string],
  RoleRevokedEventObject
>;

export type RoleRevokedEventFilter = TypedEventFilter<RoleRevokedEvent>;

export interface TokenChangedEventObject {
  key: string;
  operation: number;
}
export type TokenChangedEvent = TypedEvent<
  [string, number],
  TokenChangedEventObject
>;

export type TokenChangedEventFilter = TypedEventFilter<TokenChangedEvent>;

export interface TransferedEventObject {
  token: string;
  from: string;
  to: string;
  amount: BigNumber;
}
export type TransferedEvent = TypedEvent<
  [string, string, string, BigNumber],
  TransferedEventObject
>;

export type TransferedEventFilter = TypedEventFilter<TransferedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface WithdrewEventObject {
  token: string;
  to: string;
  amount: BigNumber;
}
export type WithdrewEvent = TypedEvent<
  [string, string, BigNumber],
  WithdrewEventObject
>;

export type WithdrewEventFilter = TypedEventFilter<WithdrewEvent>;

export interface LoanableBank extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LoanableBankInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    addAdmin(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addOperator(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addPair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addToken(
      meta: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    balances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    checkTokenAddress(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { exists: boolean }>;

    deposit(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disableLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    disablePair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAllLoans(
      overrides?: CallOverrides
    ): Promise<[Globals.LoanStructOutput[], string[]]>;

    getAllPairs(
      onlyEnabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[Globals.PairStructOutput[], string[]]>;

    getBalance(
      meta: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLTVs(
      pairs: Globals.PairStruct[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { ltvs: BigNumber[] }>;

    getLoanConfigId(
      pair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getLoanConfigKey(
      config: Globals.LoanConfigStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getLoanPreview(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [Globals.LoanStructOutput, Globals.LoanConfigStructOutput] & {
        loan: Globals.LoanStructOutput;
        config: Globals.LoanConfigStructOutput;
      }
    >;

    getPairKey(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getSupportedTokens(
      overrides?: CallOverrides
    ): Promise<
      [Bank.TokenDescriptionStructOutput[]] & {
        descriptions: Bank.TokenDescriptionStructOutput[];
      }
    >;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    liquidateLoan(
      holder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    liquidator(overrides?: CallOverrides): Promise<[string]>;

    loanConfigs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [Globals.PairStructOutput, BigNumber, BigNumber, BigNumber, boolean] & {
        tokenPair: Globals.PairStructOutput;
        interest: BigNumber;
        duration: BigNumber;
        liquidationLTV: BigNumber;
        enabled: boolean;
      }
    >;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    payLoan(
      holder: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeAdmin(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeOperator(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removePair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeToken(
      meta: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    requestLoan(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tokens(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transfer(
      meta: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferBackOffice(
      meta: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateLoans(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  OWNER_ROLE(overrides?: CallOverrides): Promise<string>;

  addAdmin(
    addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addLoanConfig(
    config: Globals.LoanConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addOperator(
    addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addPair(
    pair: Globals.PairStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addToken(
    meta: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  balances(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  checkTokenAddress(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  deposit(
    meta: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disableLoanConfig(
    config: Globals.LoanConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  disablePair(
    pair: Globals.PairStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAllLoans(
    overrides?: CallOverrides
  ): Promise<[Globals.LoanStructOutput[], string[]]>;

  getAllPairs(
    onlyEnabled: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<[Globals.PairStructOutput[], string[]]>;

  getBalance(
    meta: PromiseOrValue<string>,
    addr: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLTVs(
    pairs: Globals.PairStruct[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getLoanConfigId(
    pair: Globals.PairStruct,
    interest: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getLoanConfigKey(
    config: Globals.LoanConfigStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getLoanPreview(
    tokenPair: Globals.PairStruct,
    interest: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [Globals.LoanStructOutput, Globals.LoanConfigStructOutput] & {
      loan: Globals.LoanStructOutput;
      config: Globals.LoanConfigStructOutput;
    }
  >;

  getPairKey(
    pair: Globals.PairStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleAdmin(
    role: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getSupportedTokens(
    overrides?: CallOverrides
  ): Promise<Bank.TokenDescriptionStructOutput[]>;

  grantRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  liquidateLoan(
    holder: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  liquidator(overrides?: CallOverrides): Promise<string>;

  loanConfigs(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [Globals.PairStructOutput, BigNumber, BigNumber, BigNumber, boolean] & {
      tokenPair: Globals.PairStructOutput;
      interest: BigNumber;
      duration: BigNumber;
      liquidationLTV: BigNumber;
      enabled: boolean;
    }
  >;

  oracle(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  payLoan(
    holder: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeAdmin(
    addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeLoanConfig(
    config: Globals.LoanConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeOperator(
    addr: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removePair(
    pair: Globals.PairStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeToken(
    meta: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  requestLoan(
    tokenPair: Globals.PairStruct,
    interest: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: PromiseOrValue<BytesLike>,
    account: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tokens(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  transfer(
    meta: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferBackOffice(
    meta: PromiseOrValue<string>,
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateLoans(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    meta: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<string>;

    addAdmin(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    addOperator(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addPair(pair: Globals.PairStruct, overrides?: CallOverrides): Promise<void>;

    addToken(
      meta: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    balances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkTokenAddress(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deposit(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    disableLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    disablePair(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    getAllLoans(
      overrides?: CallOverrides
    ): Promise<[Globals.LoanStructOutput[], string[]]>;

    getAllPairs(
      onlyEnabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[Globals.PairStructOutput[], string[]]>;

    getBalance(
      meta: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLTVs(
      pairs: Globals.PairStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getLoanConfigId(
      pair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getLoanConfigKey(
      config: Globals.LoanConfigStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getLoanPreview(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [Globals.LoanStructOutput, Globals.LoanConfigStructOutput] & {
        loan: Globals.LoanStructOutput;
        config: Globals.LoanConfigStructOutput;
      }
    >;

    getPairKey(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getSupportedTokens(
      overrides?: CallOverrides
    ): Promise<Bank.TokenDescriptionStructOutput[]>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    liquidateLoan(
      holder: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    liquidator(overrides?: CallOverrides): Promise<string>;

    loanConfigs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [Globals.PairStructOutput, BigNumber, BigNumber, BigNumber, boolean] & {
        tokenPair: Globals.PairStructOutput;
        interest: BigNumber;
        duration: BigNumber;
        liquidationLTV: BigNumber;
        enabled: boolean;
      }
    >;

    oracle(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    payLoan(
      holder: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Globals.LoanStructOutput>;

    removeAdmin(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    removeOperator(
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removePair(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    removeToken(
      meta: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    requestLoan(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tokens(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    transfer(
      meta: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferBackOffice(
      meta: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateLoans(overrides?: CallOverrides): Promise<void>;

    withdraw(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminGranted(address)"(addr?: null): AdminGrantedEventFilter;
    AdminGranted(addr?: null): AdminGrantedEventFilter;

    "AdminRevoked(address)"(addr?: null): AdminRevokedEventFilter;
    AdminRevoked(addr?: null): AdminRevokedEventFilter;

    "BankerGranted(address)"(addr?: null): BankerGrantedEventFilter;
    BankerGranted(addr?: null): BankerGrantedEventFilter;

    "BankerRevoked(address)"(addr?: null): BankerRevokedEventFilter;
    BankerRevoked(addr?: null): BankerRevokedEventFilter;

    "ConfigChanged(bytes32,uint8)"(
      configKey?: null,
      operation?: null
    ): ConfigChangedEventFilter;
    ConfigChanged(configKey?: null, operation?: null): ConfigChangedEventFilter;

    "Deposited(address,address,uint256)"(
      token?: null,
      from?: null,
      amount?: null
    ): DepositedEventFilter;
    Deposited(token?: null, from?: null, amount?: null): DepositedEventFilter;

    "LoanCreated(address,bytes32,uint256,uint256)"(
      holder?: null,
      configKey?: null,
      ownedAmount?: null,
      deadline?: null
    ): LoanCreatedEventFilter;
    LoanCreated(
      holder?: null,
      configKey?: null,
      ownedAmount?: null,
      deadline?: null
    ): LoanCreatedEventFilter;

    "LoanLiquidated(address)"(holder?: null): LoanLiquidatedEventFilter;
    LoanLiquidated(holder?: null): LoanLiquidatedEventFilter;

    "LoanPaid(address,uint256,bool)"(
      holder?: null,
      paidAmount?: null,
      fullPayment?: null
    ): LoanPaidEventFilter;
    LoanPaid(
      holder?: null,
      paidAmount?: null,
      fullPayment?: null
    ): LoanPaidEventFilter;

    "OperatorGranted(address)"(addr?: null): OperatorGrantedEventFilter;
    OperatorGranted(addr?: null): OperatorGrantedEventFilter;

    "OperatorRevoked(address)"(addr?: null): OperatorRevokedEventFilter;
    OperatorRevoked(addr?: null): OperatorRevokedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "PairChanged(bytes32,uint8)"(
      configKey?: null,
      operation?: null
    ): PairChangedEventFilter;
    PairChanged(configKey?: null, operation?: null): PairChangedEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;
    RoleAdminChanged(
      role?: PromiseOrValue<BytesLike> | null,
      previousAdminRole?: PromiseOrValue<BytesLike> | null,
      newAdminRole?: PromiseOrValue<BytesLike> | null
    ): RoleAdminChangedEventFilter;

    "RoleGranted(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;
    RoleGranted(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleGrantedEventFilter;

    "RoleRevoked(bytes32,address,address)"(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;
    RoleRevoked(
      role?: PromiseOrValue<BytesLike> | null,
      account?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null
    ): RoleRevokedEventFilter;

    "TokenChanged(bytes32,uint8)"(
      key?: null,
      operation?: null
    ): TokenChangedEventFilter;
    TokenChanged(key?: null, operation?: null): TokenChangedEventFilter;

    "Transfered(address,address,address,uint256)"(
      token?: null,
      from?: null,
      to?: null,
      amount?: null
    ): TransferedEventFilter;
    Transfered(
      token?: null,
      from?: null,
      to?: null,
      amount?: null
    ): TransferedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "Withdrew(address,address,uint256)"(
      token?: null,
      to?: null,
      amount?: null
    ): WithdrewEventFilter;
    Withdrew(token?: null, to?: null, amount?: null): WithdrewEventFilter;
  };

  estimateGas: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    addAdmin(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addOperator(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addPair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addToken(
      meta: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    balances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkTokenAddress(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disableLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    disablePair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAllLoans(overrides?: CallOverrides): Promise<BigNumber>;

    getAllPairs(
      onlyEnabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBalance(
      meta: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLTVs(
      pairs: Globals.PairStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanConfigId(
      pair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanConfigKey(
      config: Globals.LoanConfigStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLoanPreview(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPairKey(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSupportedTokens(overrides?: CallOverrides): Promise<BigNumber>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    liquidateLoan(
      holder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    liquidator(overrides?: CallOverrides): Promise<BigNumber>;

    loanConfigs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    payLoan(
      holder: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeAdmin(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeOperator(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removePair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeToken(
      meta: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    requestLoan(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tokens(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transfer(
      meta: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferBackOffice(
      meta: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateLoans(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OPERATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    OWNER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addAdmin(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addOperator(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addPair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addToken(
      meta: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    balances(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkTokenAddress(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deposit(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disableLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    disablePair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAllLoans(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllPairs(
      onlyEnabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBalance(
      meta: PromiseOrValue<string>,
      addr: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLTVs(
      pairs: Globals.PairStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanConfigId(
      pair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanConfigKey(
      config: Globals.LoanConfigStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLoanPreview(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPairKey(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSupportedTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    liquidateLoan(
      holder: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    liquidator(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    loanConfigs(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    payLoan(
      holder: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeAdmin(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeLoanConfig(
      config: Globals.LoanConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeOperator(
      addr: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removePair(
      pair: Globals.PairStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeToken(
      meta: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    requestLoan(
      tokenPair: Globals.PairStruct,
      interest: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: PromiseOrValue<BytesLike>,
      account: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokens(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      meta: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferBackOffice(
      meta: PromiseOrValue<string>,
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateLoans(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      meta: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
