/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace Globals {
  export type PairStruct = {
    collateralToken: PromiseOrValue<string>;
    borrowToken: PromiseOrValue<string>;
  };

  export type PairStructOutput = [string, string] & {
    collateralToken: string;
    borrowToken: string;
  };
}

export interface MockOracleInterface extends utils.Interface {
  functions: {
    "getPairRatio((address,address))": FunctionFragment;
    "setPairRatio((address,address),uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getPairRatio" | "setPairRatio"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPairRatio",
    values: [Globals.PairStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setPairRatio",
    values: [Globals.PairStruct, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPairRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPairRatio",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MockOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPairRatio(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setPairRatio(
      pair: Globals.PairStruct,
      ratio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getPairRatio(
    pair: Globals.PairStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setPairRatio(
    pair: Globals.PairStruct,
    ratio: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPairRatio(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPairRatio(
      pair: Globals.PairStruct,
      ratio: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getPairRatio(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPairRatio(
      pair: Globals.PairStruct,
      ratio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPairRatio(
      pair: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPairRatio(
      pair: Globals.PairStruct,
      ratio: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
