/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace Globals {
  export type PairStruct = {
    collateralToken: PromiseOrValue<string>;
    borrowToken: PromiseOrValue<string>;
  };

  export type PairStructOutput = [string, string] & {
    collateralToken: string;
    borrowToken: string;
  };
}

export interface IOracleInterface extends utils.Interface {
  functions: {
    "getPairRatio((address,address))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getPairRatio"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getPairRatio",
    values: [Globals.PairStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPairRatio",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IOracle extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IOracleInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPairRatio(
      arg0: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getPairRatio(
    arg0: Globals.PairStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getPairRatio(
      arg0: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getPairRatio(
      arg0: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPairRatio(
      arg0: Globals.PairStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
